/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import communication.KontrolerKorisnickogInterfejsa;
import communication.Response;
import domain.Jezik;
import domain.Pol;
import domain.Profesor;
import domain.StepenStrucneSpreme;
import domain.Student;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Hrckok
 */
public class DodajProfesora extends javax.swing.JDialog {

    Profesor profesor;
    SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");

    /**
     * Creates new form DodajProfesora1
     */
    public DodajProfesora(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        popuniComboBoxove();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboPol = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtSurname = new javax.swing.JTextField();
        comboStepenStrucneSpreme = new javax.swing.JComboBox();
        txtBirthDay = new javax.swing.JTextField();
        comboJez = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel7.setText("Jezik");

        jLabel5.setText("Pol:");

        jLabel3.setText("Prezime:");

        jLabel6.setText("Stepen strucne spreme:");

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel8.setText("Dodaj profesora");

        comboPol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPolActionPerformed(evt);
            }
        });

        jLabel4.setText("Datum rodjenja:");

        txtId.setEnabled(false);

        btnSave.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btnSave.setText("Sacuvaj");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        comboStepenStrucneSpreme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboStepenStrucneSpremeActionPerformed(evt);
            }
        });

        comboJez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboJezActionPerformed(evt);
            }
        });

        jLabel1.setText("ID :");

        jLabel2.setText("Ime:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtId)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(txtSurname, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(txtBirthDay, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(comboPol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboStepenStrucneSpreme, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboJez, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBirthDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboPol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboStepenStrucneSpreme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboJez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboPolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPolActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            if (txtName.equals("") || txtSurname.equals("") || txtBirthDay.getText().trim().equals("") || comboPol.getSelectedItem().equals(null) || comboJez.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog(this, "Da bi ste uneli profesora morate da unesete sve podatke!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String ime = txtName.getText();
            String prezime = txtSurname.getText();
            String datumRodjenjaString = txtBirthDay.getText().trim();

            if (!proveriDatum(datumRodjenjaString, format)) {
                JOptionPane.showMessageDialog(this, "Niste pravilno uneli datum!", "Error", JOptionPane.ERROR_MESSAGE);
                System.out.println("Datum je neispravan");
                return;
            }
            Date datumRodjenja = format.parse(datumRodjenjaString);
            Date sadasnjiDatum = new Date();
            if (datumRodjenja.after(sadasnjiDatum)) {
                JOptionPane.showMessageDialog(this, "Datum rodjenja profesora ne moze biti nakon sadasnjeg datuma!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Pol pol = (Pol) comboPol.getSelectedItem();
            StepenStrucneSpreme stepen=(StepenStrucneSpreme) comboStepenStrucneSpreme.getSelectedItem();
            Jezik jezik = (Jezik) comboJez.getSelectedItem();

            Profesor profesor = new Profesor(ime, prezime, datumRodjenja, pol, jezik,stepen);

            Response response = KontrolerKorisnickogInterfejsa.getInstance().sacuvajProfesora(profesor);
            if (response.isSuccessful()) {
                JOptionPane.showMessageDialog(this, "Profesor uspešno sačuvan.");
                popuniComboBoxove();
                int answer = JOptionPane.showConfirmDialog(this, "Da li zelite da dodate jos profesora?");
                if (answer == 0) {
                    clearInputs();
                } else {
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Sistem ne može da sačuva profesora", "Greška", JOptionPane.ERROR_MESSAGE);
            }

        } catch (ParseException ex) {
            Logger.getLogger(DodajStudenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void comboStepenStrucneSpremeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboStepenStrucneSpremeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboStepenStrucneSpremeActionPerformed

    private void comboJezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboJezActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboJezActionPerformed



    public boolean proveriDatum(String unetiDatum, SimpleDateFormat format) {
        format.setLenient(false);
        try {
            format.parse(unetiDatum);
            return true;
        } catch (ParseException e) {
            return false;
        }
    }

    private void clearInputs() {
        txtName.setText(null);
        txtSurname.setText(null);
        txtBirthDay.setText(null);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox comboJez;
    private javax.swing.JComboBox comboPol;
    private javax.swing.JComboBox comboStepenStrucneSpreme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtBirthDay;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables

    private void popuniComboBoxove() {
        comboPol.setModel(new DefaultComboBoxModel(Pol.values()));
        comboStepenStrucneSpreme.setModel(new DefaultComboBoxModel(StepenStrucneSpreme.values()));
        ArrayList<Jezik> jezici = KontrolerKorisnickogInterfejsa.getInstance().ucitajSveJezike();
        for (Jezik j : jezici) {
            comboJez.addItem(j);
        }
    }
}
