/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import communication.KontrolerKorisnickogInterfejsa;
import communication.Response;
import domain.Jezik;
import domain.Pol;
import domain.Student;
import static java.lang.String.format;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Hrckok
 */
public class IzmeniStudenta extends javax.swing.JDialog {

    private ViewStudenti parentForm;
    SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");
    Student student;

    public IzmeniStudenta(java.awt.Frame parent, boolean modal, Student loadedStudent, ViewStudenti parentForm) {
        super(parent, modal);
        initComponents();
        this.parentForm = parentForm;
        this.student = loadedStudent;
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        try {
            prepareView();
        } catch (Exception ex) {
            Logger.getLogger(IzmeniStudenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBirthDay = new javax.swing.JTextField();
        comboJez = new javax.swing.JComboBox();
        txtSurname = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        comboPol = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtId.setEnabled(false);

        jLabel4.setText("Datum rodnjena:");

        jLabel5.setText("Pol");

        jLabel3.setText("Prezime:");

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel8.setText("Izmeni Studenta");

        btnSave.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btnSave.setText("IZMENI");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel7.setText("Jezik");

        jLabel1.setText("ID :");

        jLabel2.setText("Ime:");

        comboJez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboJezActionPerformed(evt);
            }
        });

        comboPol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtId)
                    .addComponent(txtName)
                    .addComponent(txtSurname)
                    .addComponent(txtBirthDay)
                    .addComponent(comboPol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboJez, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBirthDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboPol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboJez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btnSave)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prepareView() throws Exception {
        txtName.setText(student.getIme());
        txtSurname.setText(student.getPrezime());

        txtId.setText(Long.toString(student.getStudentID()));
        txtBirthDay.setText(format.format(student.getDatumRodjenja()));
        comboPol.setModel(new DefaultComboBoxModel(Pol.values()));
        comboPol.setSelectedItem(student.getPol());
        ArrayList<Jezik> jezici = KontrolerKorisnickogInterfejsa.getInstance().ucitajSveJezike();
        for (Jezik j : jezici) {
            comboJez.addItem(j);
            comboJez.setSelectedItem(student.getJezik());

        }

    }

    public boolean proveriDatum(String unetiDatum, SimpleDateFormat format) {
        format.setLenient(false);
        try {
            format.parse(unetiDatum);
            return true;
        } catch (ParseException e) {
            return false;
        }
    }

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
           // Provera da li su sva polja uneta ispravno
            if (txtName.getText().trim().equals("")
                    || txtSurname.getText().trim().equals("")
                    || txtBirthDay.getText().trim().equals("")
                    || comboPol.getSelectedItem() == null
                    || comboJez.getSelectedItem() == null
                    ) {

                JOptionPane.showMessageDialog(this, "Da bi ste izmenili profesora morate da unesete sve podatke!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String ime = txtName.getText().trim();
            String prezime = txtSurname.getText().trim();
            String datumRodjenja = txtBirthDay.getText().trim();

            if (!proveriDatum(datumRodjenja, format)) {
                JOptionPane.showMessageDialog(this, "Niste pravilno uneli datum!", "Error", JOptionPane.ERROR_MESSAGE);
                System.out.println("Datum je neispravan");
                return;
            }
            Date datumRodjenjaDate = format.parse(datumRodjenja);
            int id = Integer.parseInt(txtId.getText());
            Date currentDate = new Date();
            if (datumRodjenjaDate.after(currentDate)) {
                JOptionPane.showMessageDialog(this, "Datum rodjenja ne sme biti nakon sadasnjeg datuma!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Pol pol = (Pol) comboPol.getSelectedItem();
            Jezik j = (Jezik) comboJez.getSelectedItem();

            Student student = new Student(id, ime, prezime, datumRodjenjaDate, pol, j);

            Response response = KontrolerKorisnickogInterfejsa.getInstance().izmeniStudenta(student);
            if (response.isSuccessful()) {
                JOptionPane.showMessageDialog(this, "Student uspešno izmenjen.");
                parentForm.prepareTable();
                this.dispose();
            } else {
                 JOptionPane.showMessageDialog(this, "Sistem ne može da izmeni učenika.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void comboJezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboJezActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboJezActionPerformed

    private void comboPolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPolActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox comboJez;
    private javax.swing.JComboBox comboPol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtBirthDay;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables
}
