/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import communication.KontrolerKorisnickogInterfejsa;
import domain.Student;
import domain.TerminCasa;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.StudentTableModel;
import model.TerminCasaTableModel;

/**
 *
 * @author Hrckok
 */
public class ViewZakazaniTermini extends javax.swing.JDialog {

    List<TerminCasa> zakazaniTermini;

    /**
     * Creates new form ViewZakazaniTermini
     */
    public ViewZakazaniTermini(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        prepareTable();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblClassTime = new javax.swing.JTable();
        btnViewAllProfessors = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtByName = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btnEditProfessor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblClassTime.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblClassTime);

        btnViewAllProfessors.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnViewAllProfessors.setText("VIDI SVE TERMINE");
        btnViewAllProfessors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllProfessorsActionPerformed(evt);
            }
        });

        jLabel1.setText("Pretraži termin po imenu studenta:");

        jButton2.setText("Pretraži");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnEditProfessor.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnEditProfessor.setText("IZMENI TERMIN");
        btnEditProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProfessorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViewAllProfessors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)
                        .addComponent(txtByName, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtByName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnViewAllProfessors, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewAllProfessorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllProfessorsActionPerformed
        prepareTable();
    }//GEN-LAST:event_btnViewAllProfessorsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (!txtByName.getText().isEmpty()) {
            filterByName(txtByName.getText().trim());
        } else {
            prepareTable();

        }
    }//GEN-LAST:event_jButton2ActionPerformed
    private void filterByName(String query) {
        TerminCasa tc = new TerminCasa();
        Student st = new Student();
        st.setIme(query);
        tc.setStudent(st);
        try {
            ArrayList<TerminCasa> termini = KontrolerKorisnickogInterfejsa.getInstance().ucitajSveTermineUslov(tc);
            System.out.println(termini);

            if (termini.size() != 0) {
                ((TerminCasaTableModel) tblClassTime.getModel()).setClassTimes(termini);
                JOptionPane.showMessageDialog(this, "Sistem je našao termine po zadatoj vrednosti!");
                tblClassTime.setModel(new TerminCasaTableModel(termini));

            } else {
                JOptionPane.showMessageDialog(this, "Sistem ne može da nađe termine po zadatoj vrednosti!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

            Logger.getLogger(ViewStudenti.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void btnEditProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProfessorActionPerformed

        int selectedRow = tblClassTime.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Niste selektovali termin iz tabele! !");
            return;
        }
        TerminCasaTableModel model = (TerminCasaTableModel) tblClassTime.getModel();
        TerminCasa termin = model.getZakazaniTermini().get(selectedRow);
        TerminCasa loadTermin = new TerminCasa();
        loadTermin = KontrolerKorisnickogInterfejsa.getInstance().ucitajTermin(termin);
        if (loadTermin != null) {
             JOptionPane.showMessageDialog(this, "Sistem je uspešno učitao  termin.");
            IzmeniTermin izmeniTermin = new IzmeniTermin((Frame) this.getParent(), true, loadTermin,this);
            izmeniTermin.setVisible(true);
        }
        else {
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita termin.", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

    }//GEN-LAST:event_btnEditProfessorActionPerformed
    public void prepareTable() {
        zakazaniTermini = KontrolerKorisnickogInterfejsa.getInstance().ucitajSveZakazaneTrmine();
        tblClassTime.setModel(new TerminCasaTableModel(zakazaniTermini));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditProfessor;
    private javax.swing.JButton btnViewAllProfessors;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClassTime;
    private javax.swing.JTextField txtByName;
    // End of variables declaration//GEN-END:variables
}
