/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import communication.KontrolerKorisnickogInterfejsa;
import communication.Response;
import domain.Student;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.StudentTableModel;

/**
 *
 * @author Hrckok
 */
public class ViewStudenti extends javax.swing.JDialog {

    List<Student> studenti;

    /**
     * Creates new form ViewStudenti1
     */
    public ViewStudenti(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        prepareTable();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewAllStudents = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        btnRemoveStudent = new javax.swing.JButton();
        btnEditStudent = new javax.swing.JButton();
        btnSearchByName = new javax.swing.JButton();
        txtByName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnViewAllStudents.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnViewAllStudents.setText("VIDI SVE STUDENTE");
        btnViewAllStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllStudentsActionPerformed(evt);
            }
        });

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStudents);

        btnRemoveStudent.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnRemoveStudent.setText("IZBRISI STUDENTA");
        btnRemoveStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveStudentActionPerformed(evt);
            }
        });

        btnEditStudent.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnEditStudent.setText("IZMENI STUDENTA");
        btnEditStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditStudentActionPerformed(evt);
            }
        });

        btnSearchByName.setText("Pretraži");
        btnSearchByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Pretraga po imenu:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtByName, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchByName)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViewAllStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRemoveStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtByName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnSearchByName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnViewAllStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoveStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewAllStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllStudentsActionPerformed
        prepareTable();
    }//GEN-LAST:event_btnViewAllStudentsActionPerformed

    private void btnRemoveStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveStudentActionPerformed
        int red = tblStudents.getSelectedRow();
        if (red < 0) {
            JOptionPane.showMessageDialog(this, "Morate izabrati red!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int option = JOptionPane.showConfirmDialog(this, "Jeste li sigurni?", "Potvrda brisanja", JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION) {
            try {
                StudentTableModel model = (StudentTableModel) tblStudents.getModel();
                Student student = model.getStudents().get(red);
                Student loadStudent = KontrolerKorisnickogInterfejsa.getInstance().ucitajStudenta(student);

                if (loadStudent != null) {
                    Response responseBrisanje = KontrolerKorisnickogInterfejsa.getInstance().obrisiStudenta(loadStudent);
                    if (responseBrisanje.isSuccessful()) {
                        JOptionPane.showMessageDialog(this, "Sistem je obrisao studenta.");
                        prepareTable();
                    } else {
                        JOptionPane.showMessageDialog(this, "Sistem ne može da obriše studenta.");
                        return;
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Sistem ne može da učita učenika.", "ERROR", JOptionPane.ERROR_MESSAGE);
                    return;
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "", JOptionPane.ERROR_MESSAGE);
            }
            prepareTable();
        }
    }//GEN-LAST:event_btnRemoveStudentActionPerformed

    private void btnEditStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditStudentActionPerformed

        int selectedRow = tblStudents.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Niste selektovali studenta iz tabele! !");
            return;
        }
        StudentTableModel model = (StudentTableModel) tblStudents.getModel();
        Student student = model.getStudents().get(selectedRow);
        System.out.println(student);
        Student loadStudent = new Student();

        loadStudent = KontrolerKorisnickogInterfejsa.getInstance().ucitajStudenta(student);

        if (loadStudent != null) {
              JOptionPane.showMessageDialog(this, "Sistem je uspešno učitao  studenta.");
            IzmeniStudenta izmeniStudenta = new IzmeniStudenta((Frame) this.getParent(), true, loadStudent, this);
            izmeniStudenta.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita učenika.", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

    }//GEN-LAST:event_btnEditStudentActionPerformed

    private void btnSearchByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByNameActionPerformed
        if (!txtByName.getText().isEmpty()) {
            filterByName(txtByName.getText().trim());
        } else {
            prepareTable();

        }
    }//GEN-LAST:event_btnSearchByNameActionPerformed

    public void prepareTable() {
        studenti = KontrolerKorisnickogInterfejsa.getInstance().ucitajSveStudente();
        tblStudents.setModel(new StudentTableModel(studenti));

    }

    private void filterByName(String query) {
        Student st = new Student();
        st.setIme(query);
        try {
            ArrayList<Student> studenti = KontrolerKorisnickogInterfejsa.getInstance().ucitajSveStudenteUslov(st);
            System.out.println(studenti);

            if (studenti.size() != 0) {
                ((StudentTableModel) tblStudents.getModel()).setStudents(studenti);
                JOptionPane.showMessageDialog(this, "Sistem je našao studenta po zadatoj vrednosti!");
                tblStudents.setModel(new StudentTableModel(studenti));

            } else {
                JOptionPane.showMessageDialog(this, "Sistem ne može da nađe studenta po zadatoj vrednosti!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

            Logger.getLogger(ViewStudenti.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditStudent;
    private javax.swing.JButton btnRemoveStudent;
    private javax.swing.JButton btnSearchByName;
    private javax.swing.JButton btnViewAllStudents;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTextField txtByName;
    // End of variables declaration//GEN-END:variables
}
